### PR TITLE
Fix missing make for the lastIPs map

### LINKED ISSUE #43: panic: assignment to entry in nil map
```
May 10 22:21:01 server2 caddy[1379103]: {"level":"info","ts":1683750061.5673218,"logger":"dynamic_dns","msg":"domain not found in DNS","domain":"dyn"}
May 10 22:21:01 server2 caddy[1379103]: {"level":"info","ts":1683750061.567349,"logger":"dynamic_dns","msg":"domain not found in DNS","domain":"dyn"}
May 10 22:21:02 server2 caddy[1379103]: {"level":"info","ts":1683750062.661033,"logger":"dynamic_dns","msg":"updating DNS record","zone":"~~~","type":"A","name":"~~~","value":"~~~","ttl":0}
May 10 22:21:02 server2 caddy[1379103]: {"level":"info","ts":1683750062.6610668,"logger":"dynamic_dns","msg":"updating DNS record","zone":"~~~","type":"AAAA","name":"~~~","value":"~~~","ttl":0}
May 10 22:21:06 server2 caddy[1379103]: panic: assignment to entry in nil map
May 10 22:21:06 server2 caddy[1379103]:
May 10 22:21:06 server2 caddy[1379103]: goroutine 49 [running]:
May 10 22:21:06 server2 caddy[1379103]: github.com/mholt/caddy-dynamicdns.App.checkIPAndUpdateDNS({{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0xc00021d5c0, 0x0, 0x0, {0x0, ...}, ...})
May 10 22:21:06 server2 caddy[1379103]:         github.com/mholt/caddy-dynamicdns@v0.0.0-20230504171859-9f5dde239475/dynamicdns.go:254 +0xab1
May 10 22:21:06 server2 caddy[1379103]: github.com/mholt/caddy-dynamicdns.App.checkerLoop({{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0xc00021d5c0, 0x0, 0x0, {0x0, ...}, ...})
May 10 22:21:06 server2 caddy[1379103]:         github.com/mholt/caddy-dynamicdns@v0.0.0-20230504171859-9f5dde239475/dynamicdns.go:150 +0xb8
May 10 22:21:06 server2 caddy[1379103]: created by github.com/mholt/caddy-dynamicdns.App.Start
May 10 22:21:06 server2 caddy[1379103]:         github.com/mholt/caddy-dynamicdns@v0.0.0-20230504171859-9f5dde239475/dynamicdns.go:135 +0xaa
```

### PR DESCRIPTION
**Pull request by francislavoie**
I think this should be it?

Fix #43

### CODE REVIEW

**Review by mholt — APPROVED** [review]
Looks very well like that should do it! Is this something @namazso can test before we merge just to verify?

**Comment by francislavoie** [comment]
I'm testing myself right now, trying to figure out one thing...

**Comment by francislavoie** [comment]
Okay yeah, the joining of domain and zone is kinda messed up. I need to fix that. Domain manipulation is annoyingly complicated.

**Comment by namazso** [comment]
Well, it doesn't seem to crash, and also got a finished message now:

```

May 10 23:59:23 server2 caddy[1452948]: {"level":"info","ts":1683755963.0720408,"logger":"dynamic_dns","msg":"domain not found in DNS","domain":"~~~"}
May 10 23:59:23 server2 caddy[1452948]: {"level":"info","ts":1683755963.0720797,"logger":"dynamic_dns","msg":"domain not found in DNS","domain":"~~~"}
May 10 23:59:24 server2 caddy[1452948]: {"level":"info","ts":1683755964.5031276,"logger":"dynamic_dns","msg":"updating DNS record","zone":"~~~","type":"A","name":"~~~","value":"~~~","ttl":0}
May 10 23:59:24 server2 caddy[1452948]: {"level":"info","ts":1683755964.503158,"logger":"dynamic_dns","msg":"updating DNS record","zone":"~~~","type":"AAAA","name":"~~~","value":"~~~","ttl":0}
May 10 23:59:27 server2 caddy[1452948]: {"level":"info","ts":1683755967.7643762,"logger":"dynamic_dns","msg":"finished updating DNS","current_ips":["~~~","~~~"]}
```

**Comment by francislavoie** [comment]
The "domain not found in DNS" is a problem though. Trying to figure that part out.

**Comment by francislavoie** [comment]
Okay this should be good to merge @mholt (I don't have permissions on this repo)

**Review by mholt — APPROVED** [review]
Cool, thanks so much Francis :blush:

**Pull request merged**
